Config = {}

-- General configuration
Config.CommandName = "pedmenu" -- Command to open the ped menu

-- Categories for ped models
Config.Categories = {
    {
        name = "Animals",
        models = {
            {hash = "a_c_cat_01", label = "Cat"},
            {hash = "a_c_chop", label = "Chop"},
            {hash = "a_c_cow", label = "Cow"},
            {hash = "a_c_coyote", label = "Coyote"},
            {hash = "a_c_deer", label = "Deer"},
            {hash = "a_c_husky", label = "Husky"},
            {hash = "a_c_pig", label = "Pig"},
            {hash = "a_c_rabbit_01", label = "Rabbit"}
        }
    },
    {
        name = "Male",
        models = {
            {hash = "a_m_m_acult_01", label = "Acult"},
            {hash = "a_m_m_afriamer_01", label = "African American"},
            {hash = "a_m_m_beach_01", label = "Beach"},
            {hash = "a_m_m_bevhills_01", label = "Beverly Hills"},
            {hash = "a_m_m_bevhills_02", label = "Beverly Hills 2"},
            {hash = "a_m_m_business_01", label = "Business"},
            {hash = "a_m_m_eastsa_01", label = "East SA"},
            {hash = "a_m_m_eastsa_02", label = "East SA 2"},
            {hash = "a_m_m_farmer_01", label = "Farmer"},
            {hash = "a_m_m_fatlatin_01", label = "Fat Latin"},
            {hash = "a_m_m_genfat_01", label = "Fat"},
            {hash = "a_m_m_genfat_02", label = "Fat 2"},
            {hash = "a_m_m_golfer_01", label = "Golfer"},
            {hash = "a_m_m_hasjew_01", label = "Hasidic Jew"},
            {hash = "a_m_m_hillbilly_01", label = "Hillbilly"},
            {hash = "a_m_m_hillbilly_02", label = "Hillbilly 2"},
            {hash = "a_m_m_indian_01", label = "Indian"},
            {hash = "a_m_m_ktown_01", label = "Korean"},
            {hash = "a_m_m_malibu_01", label = "Malibu"},
            {hash = "a_m_m_mexcntry_01", label = "Mexican Country"},
            {hash = "a_m_m_mexlabor_01", label = "Mexican Labor"},
            {hash = "a_m_m_og_boss_01", label = "OG Boss"},
            {hash = "a_m_m_paparazzi_01", label = "Paparazzi"},
            {hash = "a_m_m_polynesian_01", label = "Polynesian"},
            {hash = "a_m_m_prolhost_01", label = "Prologue Host"},
            {hash = "a_m_m_rurmeth_01", label = "Rural Meth Addict"},
            {hash = "a_m_m_salton_01", label = "Salton"},
            {hash = "a_m_m_salton_02", label = "Salton 2"},
            {hash = "a_m_m_salton_03", label = "Salton 3"},
            {hash = "a_m_m_salton_04", label = "Salton 4"},
            {hash = "a_m_m_skater_01", label = "Skater"},
            {hash = "a_m_m_skidrow_01", label = "Skid Row"},
            {hash = "a_m_m_socenlat_01", label = "Socen Latin"},
            {hash = "a_m_m_soucent_01", label = "South Central"},
            {hash = "a_m_m_soucent_02", label = "South Central 2"},
            {hash = "a_m_m_soucent_03", label = "South Central 3"},
            {hash = "a_m_m_soucent_04", label = "South Central 4"},
            {hash = "a_m_m_stlat_02", label = "St Latin"},
            {hash = "a_m_m_tennis_01", label = "Tennis Player"},
            {hash = "a_m_m_tourist_01", label = "Tourist"},
            {hash = "a_m_m_trampbeac_01", label = "Tramp Beach"},
            {hash = "a_m_m_tramp_01", label = "Tramp"},
            {hash = "a_m_m_tranvest_01", label = "Transvestite"},
            {hash = "a_m_m_tranvest_02", label = "Transvestite 2"},
            {hash = "a_m_o_acult_01", label = "Acult Old"},
            {hash = "a_m_o_acult_02", label = "Acult Old 2"},
            {hash = "a_m_o_beach_01", label = "Beach Old"},
            {hash = "a_m_o_genstreet_01", label = "General Street Old"},
            {hash = "a_m_o_ktown_01", label = "Korean Old"},
            {hash = "a_m_o_salton_01", label = "Salton Old"},
            {hash = "a_m_o_soucent_01", label = "South Central Old"},
            {hash = "a_m_o_soucent_02", label = "South Central Old 2"},
            {hash = "a_m_o_soucent_03", label = "South Central Old 3"},
            {hash = "a_m_o_tramp_01", label = "Tramp Old"},
            {hash = "a_m_y_acult_01", label = "Acult Young"},
            {hash = "a_m_y_acult_02", label = "Acult Young 2"},
            {hash = "a_m_y_beachvesp_01", label = "Beach Vespucci"},
            {hash = "a_m_y_beachvesp_02", label = "Beach Vespucci 2"},
            {hash = "a_m_y_beach_01", label = "Beach Young"},
            {hash = "a_m_y_beach_02", label = "Beach Young 2"},
            {hash = "a_m_y_beach_03", label = "Beach Young 3"}
        }
    },
    {
        name = "Female",
        models = {
            {hash = "a_f_m_beach_01", label = "Beach"},
            {hash = "a_f_m_bevhills_01", label = "Beverly Hills"},
            {hash = "a_f_m_bevhills_02", label = "Beverly Hills 2"},
            {hash = "a_f_m_bodybuild_01", label = "Bodybuilder"},
            {hash = "a_f_m_business_02", label = "Business 2"},
            {hash = "a_f_m_downtown_01", label = "Downtown"},
            {hash = "a_f_m_eastsa_01", label = "East SA"},
            {hash = "a_f_m_eastsa_02", label = "East SA 2"},
            {hash = "a_f_m_fatbla_01", label = "Fat Black"},
            {hash = "a_f_m_fatcult_01", label = "Fat Cult"},
            {hash = "a_f_m_fatwhite_01", label = "Fat White"},
            {hash = "a_f_m_ktown_01", label = "Korean"},
            {hash = "a_f_m_ktown_02", label = "Korean 2"},
            {hash = "a_f_m_prolhost_01", label = "Prologue Host"},
            {hash = "a_f_m_salton_01", label = "Salton"},
            {hash = "a_f_m_skidrow_01", label = "Skid Row"},
            {hash = "a_f_m_soucent_01", label = "South Central"},
            {hash = "a_f_m_soucent_02", label = "South Central 2"},
            {hash = "a_f_m_soucentmc_01", label = "South Central MC"},
            {hash = "a_f_m_tourist_01", label = "Tourist"},
            {hash = "a_f_m_trampbeac_01", label = "Tramp Beach"},
            {hash = "a_f_m_tramp_01", label = "Tramp"},
            {hash = "a_f_o_genstreet_01", label = "General Street Old"},
            {hash = "a_f_o_indian_01", label = "Indian Old"},
            {hash = "a_f_o_ktown_01", label = "Korean Old"},
            {hash = "a_f_o_salton_01", label = "Salton Old"},
            {hash = "a_f_o_soucent_01", label = "South Central Old"},
            {hash = "a_f_o_soucent_02", label = "South Central Old 2"},
            {hash = "a_f_y_beach_01", label = "Beach Young"},
            {hash = "a_f_y_bevhills_01", label = "Beverly Hills Young"},
            {hash = "a_f_y_bevhills_02", label = "Beverly Hills Young 2"},
            {hash = "a_f_y_bevhills_03", label = "Beverly Hills Young 3"},
            {hash = "a_f_y_bevhills_04", label = "Beverly Hills Young 4"},
            {hash = "a_f_y_business_01", label = "Business Young"},
            {hash = "a_f_y_business_02", label = "Business Young 2"},
            {hash = "a_f_y_business_03", label = "Business Young 3"},
            {hash = "a_f_y_business_04", label = "Business Young 4"},
            {hash = "a_f_y_eastsa_01", label = "East SA Young"},
            {hash = "a_f_y_eastsa_02", label = "East SA Young 2"},
            {hash = "a_f_y_eastsa_03", label = "East SA Young 3"},
            {hash = "a_f_y_epsilon_01", label = "Epsilon"},
            {hash = "a_f_y_fitness_01", label = "Fitness"},
            {hash = "a_f_y_fitness_02", label = "Fitness 2"},
            {hash = "a_f_y_genhot_01", label = "General Hot"},
            {hash = "a_f_y_golfer_01", label = "Golfer"},
            {hash = "a_f_y_hiker_01", label = "Hiker"},
            {hash = "a_f_y_hippie_01", label = "Hippie"},
            {hash = "a_f_y_hipster_01", label = "Hipster"},
            {hash = "a_f_y_hipster_02", label = "Hipster 2"},
            {hash = "a_f_y_hipster_03", label = "Hipster 3"},
            {hash = "a_f_y_hipster_04", label = "Hipster 4"},
            {hash = "a_f_y_indian_01", label = "Indian Young"},
            {hash = "a_f_y_juggalo_01", label = "Juggalo"},
            {hash = "a_f_y_runner_01", label = "Runner"},
            {hash = "a_f_y_rurmeth_01", label = "Rural Meth Addict"},
            {hash = "a_f_y_scdressy_01", label = "Dressy"},
            {hash = "a_f_y_skater_01", label = "Skater"},
            {hash = "a_f_y_soucent_01", label = "South Central Young"},
            {hash = "a_f_y_soucent_02", label = "South Central Young 2"},
            {hash = "a_f_y_soucent_03", label = "South Central Young 3"},
            {hash = "a_f_y_tennis_01", label = "Tennis Player"},
            {hash = "a_f_y_tourist_01", label = "Tourist Young"},
            {hash = "a_f_y_tourist_02", label = "Tourist Young 2"},
            {hash = "a_f_y_vinewood_01", label = "Vinewood"},
            {hash = "a_f_y_vinewood_02", label = "Vinewood 2"},
            {hash = "a_f_y_vinewood_03", label = "Vinewood 3"},
            {hash = "a_f_y_vinewood_04", label = "Vinewood 4"},
            {hash = "a_f_y_yoga_01", label = "Yoga"}
        }
    },
    {
        name = "Story Characters",
        models = {
            {hash = "player_zero", label = "Michael"},
            {hash = "player_one", label = "Franklin"},
            {hash = "player_two", label = "Trevor"},
            {hash = "ig_amandatownley", label = "Amanda"},
            {hash = "ig_tracydisanto", label = "Tracy"},
            {hash = "ig_jimmydisanto", label = "Jimmy"},
            {hash = "ig_wade", label = "Wade"},
            {hash = "ig_lamar", label = "Lamar"},
            {hash = "ig_lestercrest", label = "Lester"},
            {hash = "ig_brad", label = "Brad"},
            {hash = "ig_stretch", label = "Stretch"},
            {hash = "ig_solomon", label = "Solomon"}
        }
    }
}

-- UI Colors
Config.UI = {
    colors = {
        primary = "#000000",       -- Black
        secondary = "#333333",     -- Dark Grey
        tertiary = "#666666",      -- Light Grey
        text = "#FFFFFF",          -- White
        highlight = "#888888"      -- Lighter Grey for highlights
    }
}
